"""Shared filesystem-safe-name utility for character assets.

Both the avatar helper (writes `output/images/avatars/<safe>.png`) and the
visual profile store (writes `output/characters/<safe>/profile.json`) need to
agree on how a free-form character name is sanitized — otherwise an avatar
generated by the extract endpoint and the profile written by the consistency
pipeline land under different directory keys and never link up.

The two had drifted: one used a regex `[^\\w\\- ]`-replace with truncation, the
other used a per-char `isalnum()` filter with no truncation. For Vietnamese
names they happened to converge, but names with punctuation or names >60 chars
diverged. This module is the single source of truth.
"""

from __future__ import annotations

import re

_MAX_LEN = 60
_REPLACE_RE = re.compile(r"[^\w\- ]", flags=re.UNICODE)


def safe_character_name(name: str) -> str:
    """Filesystem-safe slug for a character name. Stable across all callers.

    Rules:
      - Unicode letters/digits/underscore/hyphen pass through (so Vietnamese
        diacritics like ``ư`` survive — `re.UNICODE` makes ``\\w`` Unicode-aware).
      - Everything else (apostrophes, periods, parens, etc.) becomes ``_``.
      - Spaces collapse to ``_``.
      - Truncated to ``_MAX_LEN`` characters so we never hit Windows/Linux
        filename length limits.
      - Empty input returns ``"unnamed"`` rather than ``""`` so callers can
        always construct a valid path.
    """
    cleaned = _REPLACE_RE.sub("_", name or "").strip()
    cleaned = cleaned.replace(" ", "_")[:_MAX_LEN]
    return cleaned or "unnamed"


__all__ = ["safe_character_name"]
